import { Route, TransportMode } from './types';

export const POPULAR_CITIES = ['Hyderabad', 'Vijayawada', 'Visakhapatnam', 'Bengaluru', 'Chennai', 'Mumbai', 'Delhi'];

export const MOCK_ROUTES: Route[] = [
  // Bus Routes
  {
    id: 'B101',
    mode: TransportMode.BUS,
    number: '101',
    startLocation: 'Central Station',
    destination: 'Uptown Mall',
    startTime: '08:00',
    endTime: '08:45',
    via: ['City Hall', 'Market Street'],
    totalPrice: 2.5,
    stops: [
      { name: 'Central Station', arrivalTime: '-', departureTime: '08:00', priceFromPrevious: 0 },
      { name: 'City Hall', arrivalTime: '08:15', departureTime: '08:16', priceFromPrevious: 1.0 },
      { name: 'Market Street', arrivalTime: '08:30', departureTime: '08:31', priceFromPrevious: 1.0 },
      { name: 'Uptown Mall', arrivalTime: '08:45', departureTime: '-', priceFromPrevious: 0.5 },
    ],
    type: 'AC',
    session: 'Weekday',
    timeOfDay: 'Morning',
  },
  {
    id: 'B202',
    mode: TransportMode.BUS,
    number: '202',
    startLocation: 'Airport',
    destination: 'Downtown',
    startTime: '14:30',
    endTime: '15:30',
    via: ['Convention Center'],
    totalPrice: 5.0,
    stops: [
        { name: 'Airport', arrivalTime: '-', departureTime: '14:30', priceFromPrevious: 0 },
        { name: 'Convention Center', arrivalTime: '15:00', departureTime: '15:02', priceFromPrevious: 3.0 },
        { name: 'Downtown', arrivalTime: '15:30', departureTime: '-', priceFromPrevious: 2.0 },
    ],
    type: 'Express',
    session: 'Weekday',
    timeOfDay: 'Afternoon',
  },
    {
    id: 'B303',
    mode: TransportMode.BUS,
    number: '303',
    startLocation: 'East Suburb',
    destination: 'West Suburb',
    startTime: '19:00',
    endTime: '20:15',
    via: ['Downtown', 'University'],
    totalPrice: 3.0,
    stops: [
        { name: 'East Suburb', arrivalTime: '-', departureTime: '19:00', priceFromPrevious: 0 },
        { name: 'Downtown', arrivalTime: '19:25', departureTime: '19:30', priceFromPrevious: 1.5 },
        { name: 'University', arrivalTime: '19:50', departureTime: '19:52', priceFromPrevious: 1.0 },
        { name: 'West Suburb', arrivalTime: '20:15', departureTime: '-', priceFromPrevious: 0.5 },
    ],
    type: 'Non-AC',
    session: 'Weekend',
    timeOfDay: 'Evening',
  },

  // Train Routes
  {
    id: 'T50',
    mode: TransportMode.TRAIN,
    number: 'T50',
    startLocation: 'Grand Central',
    destination: 'Coastal City',
    startTime: '09:15',
    endTime: '11:45',
    via: ['Northgate', 'River Junction'],
    totalPrice: 25.0,
    stops: [
      { name: 'Grand Central', arrivalTime: '-', departureTime: '09:15', priceFromPrevious: 0 },
      { name: 'Northgate', arrivalTime: '10:00', departureTime: '10:05', priceFromPrevious: 10.0 },
      { name: 'River Junction', arrivalTime: '10:50', departureTime: '10:55', priceFromPrevious: 10.0 },
      { name: 'Coastal City', arrivalTime: '11:45', departureTime: '-', priceFromPrevious: 5.0 },
    ],
    type: 'Superfast',
    session: 'Weekday',
    timeOfDay: 'Morning',
  },
  {
    id: 'T75',
    mode: TransportMode.TRAIN,
    number: 'T75',
    startLocation: 'Metro Hub',
    destination: 'Mountain View',
    startTime: '21:00',
    endTime: '23:30',
    via: ['Valley Town'],
    totalPrice: 18.0,
    stops: [
        { name: 'Metro Hub', arrivalTime: '-', departureTime: '21:00', priceFromPrevious: 0 },
        { name: 'Valley Town', arrivalTime: '22:15', departureTime: '22:20', priceFromPrevious: 12.0 },
        { name: 'Mountain View', arrivalTime: '23:30', departureTime: '-', priceFromPrevious: 6.0 },
    ],
    type: 'Express',
    session: 'Weekend',
    timeOfDay: 'Night',
  },
    {
    id: 'T22',
    mode: TransportMode.TRAIN,
    number: 'T22',
    startLocation: 'South Station',
    destination: 'Industrial Park',
    startTime: '06:30',
    endTime: '07:10',
    via: ['Midtown'],
    totalPrice: 4.5,
    stops: [
        { name: 'South Station', arrivalTime: '-', departureTime: '06:30', priceFromPrevious: 0 },
        { name: 'Midtown', arrivalTime: '06:50', departureTime: '06:52', priceFromPrevious: 2.5 },
        { name: 'Industrial Park', arrivalTime: '07:10', departureTime: '-', priceFromPrevious: 2.0 },
    ],
    type: 'Local',
    session: 'Weekday',
    timeOfDay: 'Morning',
  },
];

export const FILTER_OPTIONS = {
  type: ['AC', 'Non-AC', 'Express', 'Superfast', 'Local'],
  time: ['Morning', 'Afternoon', 'Evening', 'Night'],
  session: ['Weekday', 'Weekend'],
};